### ISSUE TITLE
employeeNumber is missing. 

### ISSUE THREAD

**Issue by JeroenTielen** [RobBridgeman/ADImporter#3]
Hi Rob, 

There is something missing in the current version. Declaration of employeenumber is not there anymore. If I copy it from the original script from Helge then is works again. 

I've copied this from the Helge script:    $employeeNumber = Get-Random -Minimum 100000 -Maximum 1000000

And the second issue is that the scripts only loops in the lastname "foreach loop". 
Here is something not correct ;) 

```
# Sex & name
$i = 0
if ($i -lt $userCount) 
{
    foreach ($firstname in $firstNames)
{
    foreach ($lastname in $lastnames)
    {
    $Fname = $firstname.Firstname
    $Lname = $lastName.Lastname
```

Best regards, Jeroen.

**Comment by zpfln** [comment]
I had to add the line below into the "user variables" or the creation of the variable $sAMAccountName fails and the whole script fails...

$employeeNumber = 1

I assume in Helge's version, as mentioned above by JeroenTielen, has a randomer instead of a incremental...

**Comment by SHSauler** [comment]
Please merge this issue! This threw me off as well. Thanks!

**Comment by RobBridgeman** [comment]
Merged. Totally didnt forget about this repo at all. Better late than never! 😇 Thanks for the fix @bunchc
