### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by bobsmith3000** [RobBridgeman/ADImporter#7]
Hello everyone, this is most certainly a user issue, but unless there is some sort of "comments" section I've missed I don't know how else to ask for assistance. 

Doesn't matter what I try with this I get the below error:

New-ADUser : The server is unwilling to process the request
At C:\Users\markadmin\Desktop\New folder\CreateDemoUsers.ps1:177 char:7
+   New-ADUser -SamAccountName $sAMAccountName -Name $displayName - ...
+   CategoryInfo          : NotSpecified: (CN=Bangji Jaiba...rktest,DC=Local:String) [New-ADUser], ADException+ FullyQualifiedErrorId : ActiveDirectoryServer:0,Microsoft.ActiveDirectory.Management.Commands.NewADUser

Is anyone able or willing to suggest why ?

**Comment by ghost** [comment]
Hi Bob,

Just a guess, but from the CategoryInfo statement it looks like the value being sent for -Path is not complete.
Based on this question<https://serverfault.com/questions/639536/new-aduser-adexception-notspecified> from serverfault.com, here are some examples:
N=Users,DC=domain,DC=com

OU=MyOU,DC=domain,DC=com

OU=SubOU,OU=MyOU,DC=subdomain,DC=domain,DC=com

Hope that helps.

Kind regards,

Jordan


Jordan Olin
Professional Services Consultant
+1 801 505 6880

**Comment by bobsmith3000** [comment]
Hi, yes that was the issue actually, I had some sort of brain-fade regarding distinguished names. Thanks you for your assistance.
